#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\033[0;33m"
echo "***************************************************"
echo ""
echo "We use branch-name-lint."
echo "To push a branch, be sure you have right prefix, ticket name in uppercase, and description split by underscore. Example branch name:"
echo ""
echo "  * task/01-api_models"
echo ""
echo "Read more: https://github.com/barzik/branch-name-lint"
echo ""
echo "***************************************************"
echo "\033[0m"

echo "\033[0;33m"
echo "***************************************************"
echo ""
echo "Lint time can be long for the first time."
echo ""
echo "***************************************************"
echo "\033[0m"

echo "Content of .brachlintrc.json:"
cat .branchlintrc.json

npx branch-name-lint --config  .brachlintrc.json
