#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\033[0;33m"
echo "***************************************************"
echo ""
echo "We use branch-name-lint."
echo "To push a branch, be sure you have right prefix (task), the two-digit task number, dash(-) and task name."
echo ""
echo "Example of a branch name:  ---> task/01-api_models <---"
echo ""
echo "Read more: https://github.com/barzik/branch-name-lint"
echo ""
echo "***************************************************"
echo "\033[0m"

echo "\033[0;33m"
echo "***************************************************"
echo ""
echo "Lint time can be long for the first time."
echo ""
echo "***************************************************"
echo "\033[0m"

cd "$(git rev-parse --show-toplevel)" || exit
docker-compose run --rm frontend npx branch-name-lint .branchlintrc.json
